apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gb-ingress
  namespace: gb
  annotations:
    kubernetes.io/ingress.class: nginx-nci-service-ingress-default
    meta.helm.sh/release-name: gb
    meta.helm.sh/release-namespace: gb
spec:
  tls:
    - hosts:
        - ui.mcs-pta.mcs.expandium.com
  rules:
    - host: ui.mcs-pta.mcs.expandium.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: guestbook-ui
                port:
                  number: 80
